//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web03.NBTIN.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web03.NBTIN.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được phép trùng.
        /// </summary>
        public static string AssetCodeDuplicateValidate {
            get {
                return ResourceManager.GetString("AssetCodeDuplicateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được bỏ trống.
        /// </summary>
        public static string AssetCodeValidate {
            get {
                return ResourceManager.GetString("AssetCodeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được bỏ trống.
        /// </summary>
        public static string AssetNameValidate {
            get {
                return ResourceManager.GetString("AssetNameValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được phép trùng.
        /// </summary>
        public static string CategoryCodeDuplicateValidate {
            get {
                return ResourceManager.GetString("CategoryCodeDuplicateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được bỏ trống.
        /// </summary>
        public static string CategoryCodeValidate {
            get {
                return ResourceManager.GetString("CategoryCodeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải không âm và khác rỗng.
        /// </summary>
        public static string CategoryDeprerateValidate {
            get {
                return ResourceManager.GetString("CategoryDeprerateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian sử dụng phải là số lớn hơn 0.
        /// </summary>
        public static string CategoryLifetimeValidate {
            get {
                return ResourceManager.GetString("CategoryLifetimeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản không được bỏ trống.
        /// </summary>
        public static string CategoryNameValidate {
            get {
                return ResourceManager.GetString("CategoryNameValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá phải lớn hơn 0.
        /// </summary>
        public static string CostValidate {
            get {
                return ResourceManager.GetString("CostValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được bỏ trống.
        /// </summary>
        public static string DepartmentCodeValidate {
            get {
                return ResourceManager.GetString("DepartmentCodeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được bỏ trống.
        /// </summary>
        public static string DepartmentNameValidate {
            get {
                return ResourceManager.GetString("DepartmentNameValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải lớn hơn 0.
        /// </summary>
        public static string DepreciationRateValidate {
            get {
                return ResourceManager.GetString("DepreciationRateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được phép trùng.
        /// </summary>
        public static string DuplicateDepartmentCodeValidate {
            get {
                return ResourceManager.GetString("DuplicateDepartmentCodeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi, liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string Error_Validate {
            get {
                return ResourceManager.GetString("Error_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LifeTimeValidate {
            get {
                return ResourceManager.GetString("LifeTimeValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy id này.
        /// </summary>
        public static string NotValidId {
            get {
                return ResourceManager.GetString("NotValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu sử dụng không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string ProductionYearValidate {
            get {
                return ResourceManager.GetString("ProductionYearValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được bỏ trống.
        /// </summary>
        public static string PurchaseDateValidate {
            get {
                return ResourceManager.GetString("PurchaseDateValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn 0.
        /// </summary>
        public static string QuantityValidate {
            get {
                return ResourceManager.GetString("QuantityValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm theo dõi không được lớn hơn năm hiện tại.
        /// </summary>
        public static string TrackedYearValidate {
            get {
                return ResourceManager.GetString("TrackedYearValidate", resourceCulture);
            }
        }
    }
}
